# Generated by Django 4.0.4 on 2022-06-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_sessions', '0003_auto_20161205_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='client',
            field=models.JSONField(blank=True, null=True, verbose_name='client'),
        ),
    ]
